### ISSUE TITLE
cannot install on bluemix Node-Red Boilerplate

### ISSUE THREAD

**Issue by fmanclossi** [jeancarl/node-red-contrib-virtual-tjbot#1]
Activate a new Node-Red boilerplate with a fresh account (location London)
Started Node-Red
push Install to add node-red-contrib-virtual-tjbot to palette
... and Cloud Foundry Apps died :(

Any idea?

**Comment by jeancarl** [comment]
What do the (Cloud Foundry) error logs in IBM Cloud show?

**Comment by fmanclossi** [comment]
Hi, seems that the problems are related to London DC. Errors log just report TCP connection issues :(
